name: scan-commit-with-vulnerable-dependency
description: Scan a commit to check if it adds a vulnerability to the dependencies of a repo
author: pedrolacerda
branding:
  icon: 'package'  
  color: 'green'
runs:
  using: 'node12'
  main:  'index.js'
