name: scan-commit-with-vulnerable-dependency
description: Scan a commit to check if it adds a vulnerability to the dependencies of a repo
author: pedrolacerda
branding:
  icon: 'package'  
  color: 'green'
outputs:
  severity:
    desciption: 'Severity of the vulnerability'
  patchedVersion:
    description: 'First patched version'
  vulnerableVersion:
    description: 'Vulnerable version range'
runs:
  using: 'node12'
  main:  'index.js'
